config/routes.rb
Rails.application.routes.draw do
  root "questions#index"
  resources :questions do
    resources :answers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
end

app/models/answer.rb
class Answer < ApplicationRecord
  validates :body, null: false

  belongs_to :question  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question <ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true

  has_many :answers 
end

app/controllers/answers_controller.rb
class AnswerController < ApplicationController
  def new
    id=params[:question_id]
    @question=Question.find[id]
    @answer=Answer.new
  end

  def create
    id=params[:question_id]
    @answer=Answer.new(answers_params)
    @question=Question.find(id)
    @answer=question=@question
    if answer.save
      flash[:sucess] = "success"
      redirect_to @question
    else
      flash[:error] = "error"
      redirect_to @question
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def show
    id=params[:id]
    @question = Question.find(id)
    @answer=Answer.new
    @answers=@question.answers
  end

  def new
    @question=Question.new
  end

  def create
    @question=Question.new(questions_params)
    if @question.save
      flash[:success] = "Success"
      redirect_to questions_path
    else
      flash[:error] = "Error!"
      render action: 'new'
    end
  end

  def edit
    id=params[:id]
    @question=Question.find(id)
  end

  def update
    id=params[:id]
    @question=Question.find(id)
    @question.update_attributes(questions_params)
    redirect_to @question
  end

  def destroy
    id=params[:id]
    @question = Question.find(id)
    @question.destroy
    @question.answers.destroy_all
    redirect_to questions_path
  end

  private

  def questions_params
    params.require(:question).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash.html.erb
  <% flash.each do |type, message| %>
  <div>
    <strong><% type %></strong>: <% message %>
    </div>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RescueMission</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/edit.html.erb
<% form_for [@question] do |f| %>

<div>
<% f.label :title %>
<% f.text_field :title %>
</div>

<div>
<% f.label :body %>
<% f.text_field :body %>
</div>

<div>
  <% f.submit %>
</div>
<% end %>

<% link_to 'Delete Question', @question, method: :delete %>

app/views/questions/index.html.erb
<% render "layouts/flash" %>

<h1>Questions</h1>

<% link_to 'Post New Question', new_question_path %>

</br>
</br>
</br>

<ul>
  <% @questions.each do |question| %>
  <li><%= link_to question.title, question_path(question) %></li>
</br>
</ul>
  <% end $>

app/views/questions/new.html.erb
<% form_for [@question] do |f| %>

<div>
<% f.label :title %>
<% f.text_field :title %>
</div>

<div>
<% f.label :body %>
<% f.text_field :body %>
</div>

<div>
  <% f.submit %>
</div>

<% render "layouts/flash" %>

<% end %>

app/views/questions/show.html.erb
<% render "Layouts/flash" %>

<h3>@question.title<h3>
  <% link_to "delete question", @question, method: :delete %>

  <h4>Description <% @question.body %></h4>

  <% @anwers.each do |a| %>
  <p>
    <% a.body %>
  </p>
  <% end %>

  <h5>Answer this Question:</h5>
    <% forms_for [@question, @answer] do |f| %>
    <div>
      <% f.label 'Answer:', :body %>
      <% f.text_field :body %>
    </div>
    <div>
      <% f.submit %>
    </div>

    <% link_to 'index', questions_path %>
    <% link_to 'Edit Question', edit_question_path %>